def build(bld):
	sources = [
		"expand_core.c",
		"heredoc_helpers.c",
		"cmd_handler.c",
		"expand_utils.c",
		"quote_utils.c",
		"entrypoint.c",
		"handling_utils.c",
	]
	lexec = bld.objects(
		source		= sources,
		features	= "c",
		target		= "execobjs",
		includes	= bld.env.INCLUDES_ROOT,
		use			= "ft builtinsobjs"
	)
	bld.recurse("builtins")
