def build(bld):
	sources = [
		"parser.c",
		"parser_check.c",
		"parser_utils.c",
	]
	lparse = bld.objects(
		source		= sources,
		features	= "c",
		target		= "parserobjs",
		use			= "tokenobjs",
		includes	= bld.env.INCLUDES_ROOT
	)
	bld.recurse("token")
