def build(bld):
	sources = [
		"redir_manipulator.c",
		"scheduler_utils.c",
		"heredoc_utils.c",
		"piping_utils.c",
		"redir_utils.c",
		"scheduler.c",
	]
	lschedule = bld.objects(
		source		= sources,
		features	= "c",
		target		= "scheduleobjs",
		includes	= bld.env.INCLUDES_ROOT
	)
