def build(bld):
	sources = [
		"main.c"
	]
	lminishsources = [
		"utils.c"
	]
	minishell = bld.program(
		source		= sources,
		features	= "c",
		target		= "minishell",
		includes	= bld.env.INCLUDES_ROOT,
		use			= "minish ft"
	)
	lminishell = bld.stlib(
		source		= lminishsources,
		features	= "c",
		target		= "minish",
		includes	= bld.env.INCLUDES_ROOT,
		use			= "execobjs parserobjs tokenobjs"
	)
	bld.recurse("exec")
	bld.recurse("parser")
